version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tasklyapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasksapi
      MYSQL_USER: tasksuser
      MYSQL_PASSWORD: taskspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasklyapi_app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=tasklyapi_mysql
      - DB_PORT=3306
      - DB_USER=tasksuser
      - DB_PASSWORD=taskspassword
      - DB_NAME=tasksapi
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app_network
    depends_on:
      mysql:
        condition: service_healthy
    command: ["npm", "run", "start"]

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge