services:
  mysql:
    image: mysql:8.0
    container_name: tasklyapi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasksapi
      MYSQL_USER: tasksuser
      MYSQL_PASSWORD: taskspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge